aws_region                = "eu-west-1"
bucket_name               = "cmtr-fnt8937l-bucket-1780589967"
iam_group_name            = "cmtr-fnt8937l-iam-group"
iam_policy_name           = "cmtr-fnt8937l-iam-policy"
iam_role_name             = "cmtr-fnt8937l-iam-role"
iam_instance_profile_name = "cmtr-fnt8937l-iam-instance-profile"
project_id                = "cmtr-fnt8937l"
